### Teste no pc Importar arquivo XLS

POST http://localhost:8080/importar-xls
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Reconfile fornecedores.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< /home/erasmo/GITHUB/enube_projeto/base/Reconfile fornecedores.xlsx
--WebAppBoundary-- 

### Teste no notebook Importar arquivo XLS

POST http://localhost:8080/importar-xls
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Reconfile fornecedores.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

<  /mnt/85323068-cdcb-4c58-a5c6-7d2e51f42d54/GITHUB/enube_projeto/base/Reconfile fornecedores.xlsx
--WebAppBoundary-- 