@baseUrl = http://localhost:8080

### Registro de novo usuário
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "username": "erasmo",
    "email": "erascardsilva@gmail.com",
    "password": "master3727"
}

### Login e obtenção do token JWT
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username": "erasmo",
    "password": "master3727"
}

### Listar todos os usuários (com paginação)
GET {{baseUrl}}/api/users?page=1&limit=10
Authorization: Bearer {{login.response.body.token}}

### Importar arquivo Excel
POST {{baseUrl}}/api/import
Authorization: Bearer {{login.response.body.token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="Reconfile fornecedores.xlsx"
Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet

< ./base/Reconfile fornecedores.xlsx
------WebKitFormBoundary--

### Listar todos os clientes (com paginação)
GET {{baseUrl}}/api/clients?page=1&limit=10
Authorization: Bearer {{login.response.body.token}}

### Listar todas as categorias (com paginação)
GET {{baseUrl}}/api/categories?page=1&limit=10
Authorization: Bearer {{login.response.body.token}}

### Listar todos os recursos (com paginação)
GET {{baseUrl}}/api/resources?page=1&limit=10
Authorization: Bearer {{login.response.body.token}}

### Listar todos os faturamentos (com paginação)
GET {{baseUrl}}/api/billing?page=1&limit=10
Authorization: Bearer {{login.response.body.token}}

### Resumo de faturamento por categoria
GET {{baseUrl}}/api/billing/summary/categories
Authorization: Bearer {{login.response.body.token}}

### Resumo de faturamento por recursos
GET {{baseUrl}}/api/billing/summary/resources
Authorization: Bearer {{login.response.body.token}}

### Resumo de faturamento por clientes
GET {{baseUrl}}/api/billing/summary/clients
Authorization: Bearer {{login.response.body.token}}

### Resumo de faturamento por meses
GET {{baseUrl}}/api/billing/summary/months
Authorization: Bearer {{login.response.body.token}}

