# Erasmo Cardoso da Silva
# Desenvolvedor Full Stack
version: '3.8'

services:
  db:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: enube
    ports:
      - "5432:5432"
    volumes:
      # - postgres_data:/var/lib/postgresql/data # Removido para evitar persistência
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: golang-backend
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: enube
      DB_PORT: 5432
      ENVIRONMENT: development
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  # frontend:
  #   build: ./frontend
  #   container_name: react-frontend
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
  #   networks:
  #     - appnet

networks:
  app-network:
    driver: bridge

# volumes:
#   postgres_data: # Removido a definição do volume nomeado
