version: '3'

tasks:
  build:
    desc: Build the application
    cmds:
      - go build -o bin/importer cmd/importer/main.go

  run:
    desc: Run the importer
    cmds:
      - go run cmd/importer/main.go {{.FILE}} {{.BATCH}}
    vars:
      FILE: '{{default "data/input.xlsx" .FILE}}'
      BATCH: '{{default "1000" .BATCH}}'

  test:
    desc: Run tests
    cmds:
      - go test ./...

  lint:
    desc: Run linter
    cmds:
      - golangci-lint run

  tidy:
    desc: Tidy go modules
    cmds:
      - go mod tidy

  dev:
    desc: Run in development mode with hot reload
    cmds:
      - air -c .air.toml

  db:
    desc: Run database migrations
    cmds:
      - psql -U postgres -d enube -f init.sql

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - go clean 